In [ ]:
# with open('../Data/dataset.txt','r') as sentence:
#     dataset = sentence.read().splitlines() 
# this will read the file and split it into a list of sentences, where each sentence is an element in the list. 
# The splitlines() method is used to split the text at new line characters, effectively creating a list of sentences from the file.

In [139]:
import tensorflow as tf

In [140]:
file = tf.keras.utils.get_file(
    'shakespeare.txt',
    'https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt'
)

1115394/1115394 ━━━━━━━━━━━━━━━━━━━━ 1s 1us/step


In [141]:
text = open(file, 'rb').read().decode(encoding='utf-8')

In [143]:
text = text.lower()

In [ ]:
lines = text.split('\n') # outputs a list of lines seperated by new line characters

In [146]:
dataset = []

In [147]:
for line in lines:
    line = line.strip() # removes leading and trailing whitespace characters from the line
    if len(line.split()) >= 5: # checks if the line has 5 or more words 
        dataset.append(line) # adds the line to the dataset list if it has 5 or more characters

In [ ]:
dta

In [151]:
dataset = dataset[:500]

In [152]:
len(dataset)

500

In [153]:
dataset[:10]


['before we proceed any further, hear me speak.',
 'you are all resolved rather to die than to famish?',
 'first, you know caius marcius is chief enemy to the people.',
 "let us kill him, and we'll have corn at our own price.",
 "no more talking on't; let it be done: away, away!",
 'we are accounted poor citizens, the patricians good.',
 'what authority surfeits on would relieve us: if they',
 'would yield us but the superfluity, while it were',
 'wholesome, we might guess they relieved us humanely;',
 'but they think we are too dear: the leanness that']

In [154]:
lengths = []
for item in dataset:
    lengths.append(len(item.split(' ')))
max_length = max(lengths)
max_length

12

In [155]:
dataset[1]

'you are all resolved rather to die than to famish?'

In [156]:
lengths[:5]

[8, 10, 11, 12, 10]

## Integer Encoading

In [157]:
import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

In [160]:
tokenizer = Tokenizer(oov_token='<nothing>')

In [161]:
tokenizer.fit_on_texts(dataset)

In [ ]:
# The word_counts attribute of the Tokenizer object is a dictionary where the keys are the unique words 
# in the dataset and the values are the number of times each word appears in the dataset.
tokenizer.word_counts

In [163]:
# total number of sentences in the dataset
tokenizer.document_count

500

In [164]:
# The word_index attribute of the Tokenizer object is a dictionary where the keys are the unique words 
# in the dataset and the values are the corresponding integer indices assigned to each word by the tokenizer.
tokenizer.word_index

{'<nothing>': 1,
 'the': 2,
 'and': 3,
 'you': 4,
 'to': 5,
 'i': 6,
 'in': 7,
 'of': 8,
 'a': 9,
 'that': 10,
 'he': 11,
 'it': 12,
 'with': 13,
 'not': 14,
 'your': 15,
 'is': 16,
 'they': 17,
 'our': 18,
 'for': 19,
 'my': 20,
 'have': 21,
 'we': 22,
 'as': 23,
 'his': 24,
 'are': 25,
 'him': 26,
 'but': 27,
 'what': 28,
 'their': 29,
 'me': 30,
 'us': 31,
 'good': 32,
 'than': 33,
 'be': 34,
 'this': 35,
 'would': 36,
 'will': 37,
 'all': 38,
 'was': 39,
 'marcius': 40,
 'at': 41,
 'no': 42,
 'on': 43,
 'if': 44,
 'shall': 45,
 'more': 46,
 'from': 47,
 'were': 48,
 'well': 49,
 'which': 50,
 'so': 51,
 'do': 52,
 'make': 53,
 'them': 54,
 "o'": 55,
 'one': 56,
 'when': 57,
 'how': 58,
 'did': 59,
 'these': 60,
 'like': 61,
 'yet': 62,
 'or': 63,
 'go': 64,
 'by': 65,
 'then': 66,
 'rome': 67,
 'know': 68,
 'an': 69,
 'must': 70,
 "i'll": 71,
 'see': 72,
 'upon': 73,
 'thou': 74,
 'forth': 75,
 "'tis": 76,
 'come': 77,
 'let': 78,
 'say': 79,
 'where': 80,
 'had': 81,
 'now': 82,
 

In [165]:
len(tokenizer.word_index)
# total number of unique words in the dataset

1269

In [166]:
dataset[0]

'before we proceed any further, hear me speak.'

In [ ]:
tokenizer.texts_to_sequences('the teacher is on the box')

# When we pass a plain string, TensorFlow treats it as an iterable of characters:
# ['t', 'h', 'e', ' ', 't', 'e', ...]
# To get the expected behavior, we need to pass a list of strings, even if it's just one string:

In [168]:
tokenizer.texts_to_sequences(['the stupid teacher keeps smoking cigeratte'])
# allways remember that the output is a list of lists, where each inner list corresponds to the tokenized version of the input string.

[[2, 1, 1, 1, 1080, 1]]

In [171]:
tokenizer.texts_to_sequences(dataset[:5])

[[148, 22, 185, 186, 257, 89, 30, 96],
 [4, 25, 38, 422, 122, 5, 258, 33, 5, 259],
 [90, 4, 68, 187, 40, 16, 423, 188, 5, 2, 189],
 [78, 31, 424, 26, 3, 149, 21, 150, 41, 18, 123, 425],
 [42, 46, 426, 260, 78, 12, 34, 107, 124, 124]]

### forming the chain of words to predict the next

In [172]:
len([[1,5,7,2]])

1

In [173]:
sequence = []
# allways remember that the output is a list of lists, where each inner list corresponds to the tokenized version of the input string.

for sentence in dataset:

    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        sequence.append(tokenized_sentence[:i+1])

In [177]:
sequence[:16]

[[148, 22],
 [148, 22, 185],
 [148, 22, 185, 186],
 [148, 22, 185, 186, 257],
 [148, 22, 185, 186, 257, 89],
 [148, 22, 185, 186, 257, 89, 30],
 [148, 22, 185, 186, 257, 89, 30, 96],
 [4, 25],
 [4, 25, 38],
 [4, 25, 38, 422],
 [4, 25, 38, 422, 122],
 [4, 25, 38, 422, 122, 5],
 [4, 25, 38, 422, 122, 5, 258],
 [4, 25, 38, 422, 122, 5, 258, 33],
 [4, 25, 38, 422, 122, 5, 258, 33, 5],
 [4, 25, 38, 422, 122, 5, 258, 33, 5, 259]]

In [ ]:
# printing specific words corresponding to their indices in the tokenizer's word index
tokenizer.index_word[1020]  # This will print the word corresponding to index 1020 in the tokenizer's word index.

'threshold'

In [181]:
len(sequence)

3575

## Padding

In [182]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [183]:
max_length

12

In [184]:
pad_sequences = pad_sequences(sequence, maxlen=max_length, padding='pre')

In [185]:
pad_sequences[:5]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 148,  22],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 148,  22, 185],
       [  0,   0,   0,   0,   0,   0,   0,   0, 148,  22, 185, 186],
       [  0,   0,   0,   0,   0,   0,   0, 148,  22, 185, 186, 257],
       [  0,   0,   0,   0,   0,   0, 148,  22, 185, 186, 257,  89]],
      dtype=int32)

## Break into X and Y

In [186]:
X = pad_sequences[:, 0:-1]

In [187]:
X[:5]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 148],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 148,  22],
       [  0,   0,   0,   0,   0,   0,   0,   0, 148,  22, 185],
       [  0,   0,   0,   0,   0,   0,   0, 148,  22, 185, 186],
       [  0,   0,   0,   0,   0,   0, 148,  22, 185, 186, 257]],
      dtype=int32)

In [188]:
Y = pad_sequences[:, -1]

In [189]:
pad_sequences[-1]

array([   0,    0,    0,    0,    0,   23,   13,    9,   86, 1268,  421,
       1269], dtype=int32)

In [190]:
pad_sequences[2512]

array([  0,   0,   0,   0,   0, 114,  42,  65,  15, 315,  71,  14],
      dtype=int32)

In [191]:
Y[:5]

array([ 22, 185, 186, 257,  89], dtype=int32)

In [192]:
Y[:5]

array([ 22, 185, 186, 257,  89], dtype=int32)

In [193]:
X.shape

(3575, 11)

In [194]:
Y.shape

(3575,)

In [195]:
from tensorflow.keras.utils import to_categorical

In [196]:
len(tokenizer.word_index)
# here we have 78 unique words
# so after one-hot encoding, we will have 78 columns in the output for each word in the vocabulary. 

1269

In [197]:
Y = to_categorical(Y, num_classes=len(tokenizer.word_index)+1)

# here we have done categorical encoding of the target variable Y, which is necessary for training a neural network model 
# for multi-class classification because the output layer of the model will have as many neurons as there are unique words in the dataset, 
# and each neuron will represent a class corresponding to a specific word.

# this is also known as one-hot encoding, where each class (word) is represented as a binary vector with a single high (1) 
# value and the rest low (0) values.

# for example,
# if we have 5 unique words in the dataset, and the target variable Y has a value of 3 
# (which corresponds to the 3rd word in the tokenizer's word index),
# the one-hot encoded vector for that target variable would be [0, 0, 1, 0, 0], 
# where the 1 is in the position corresponding to the 3rd word in the tokenizer's word index.

# our model output will be a probability distribution over all the unique words in the dataset, and the one-hot encoded target variable 
# will allow us to calculate the loss and update the model weights during training.


# here using LSTM we are solving a classification problem, where the model will learn to predict the next word in a sequence based 
# on the previous words. Since the output is a categorical variable (the next word), we need to convert it into a format that can
#  be used for training the model, which is what to_categorical does by converting the integer labels into a binary matrix representation.

In [198]:
Y[0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(1270,))

## LSTM

In [199]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense

In [200]:
model1 = Sequential([
    Input(shape=(11,)),  # Each input sample is a sequence of 11 token IDs
    Embedding(input_dim=1270, output_dim=64),
    # Converts each token ID into a 64-dimensional dense vector
    # Output shape: (batch_size, 11, 64)

    # LSTM(100, return_sequences=True),
    # Processes the embedded sequence and returns the hidden state at every time step
    # Output shape: (batch_size, 6, 25)

    LSTM(64),
    # Processes the sequence of hidden states from the previous LSTM
    # Since return_sequences=False by default, only the final hidden state is returned
    # Output shape: (batch_size, 10)

    Dense(1270, activation='softmax')
    # Produces a probability distribution over the 79-word vocabulary
    # Output shape: (batch_size, 79)
])

In [201]:
model1.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 11, 64)         │        81,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_25 (LSTM)                  │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 1270)           │        82,550 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 196,854 (768.96 KB)

 Trainable params: 196,854 (768.96 KB)

 Non-trainable params: 0 (0.00 B)

In [202]:
model1.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [203]:
history1 = model1.fit(X, Y, epochs=100, verbose=1)

Epoch 1/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.0397 - loss: 6.6807
Epoch 2/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.0425 - loss: 6.1946
Epoch 3/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0425 - loss: 6.0700
Epoch 4/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0425 - loss: 5.9877
Epoch 5/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0425 - loss: 5.9253
Epoch 6/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0425 - loss: 5.8785
Epoch 7/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0428 - loss: 5.8368
Epoch 8/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0436 - loss: 5.7965
Epoch 9/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0445 - loss: 5.7552
Epoch 10/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0476 - loss: 5.7162
Epoch 11/100
112/112 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.0456 - loss: 5.6767
Epoch 12/100
112/112 ━━━━━━━━━━━━━━━━━━━━